---
title: "HW6 Telemarketing"
author: "Group 7 Nihal Kurki, Nelvin Vincent, Wendy Liu & Mack Khoo"
date: "3/22/2020"
output:
  html_document:
    toc: true
    theme: readable
    highlight: tango
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading and Prepping the Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
# 0 = never called, 1 = called before
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
tele_random <- telemm[sample(nrow(telemm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
tele_norm <- as.data.frame(lapply(tele_random, normalize))
```


## Getting Train and Test Samples (KNN)

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(tele_norm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
tele_train <- tele_norm[-test_set, -match("yyes",names(tele_norm))]
tele_test <- tele_norm[test_set, -match("yyes",names(tele_norm))]

# tele_train$yyes <- NULL
# tele_test$yyes <- NULL

#Now the response (aka Labels) - only the yyes column
tele_train_labels <- tele_norm[-test_set, "yyes"]
tele_test_labels <- tele_norm[test_set, "yyes"]

#Lets run the KNN command
library(class)
library(caret)

#Run KNN on train data, create predictions for test data
#Starting K value close to sqrt(nrow(alcohol2_train))
sqrt(nrow(tele_train))

KNN_tele_model <- knn(train = tele_train, test = tele_test,
                      cl = tele_train_labels, k=177)

KNN_yyes_pred <- ifelse(KNN_tele_model == "0", 0, 1)

#Evaluate model results
library(gmodels)
CrossTable(x = tele_test_labels, y = KNN_tele_model, prop.chisq=FALSE)

confusionMatrix(as.factor(KNN_tele_model), as.factor(tele_test_labels), positive = "1")

```

> Now you are ready to build your ANN model. Feel free to modify the data load, cleaning and preparation code above as per your preference.

## Build an ANN model
```{r, cache = TRUE} 
test_set <- sample(1:nrow(tele_norm), 10000) 

tele_norm_train <- tele_norm[-test_set, ]
tele_norm_test <- tele_norm[test_set, ]

library(neuralnet)

# simple ANN with only a single hidden neuron
ANN_tele_model <- neuralnet(formula = yyes ~. ,
                              data = tele_norm_train)

model_results <- compute(ANN_tele_model, tele_norm_test[1:53])

predicted_y <- model_results$net.result

prediction <-predict(ANN_tele_model, tele_norm_test)

prediction

ANN_yyes_pred <- ifelse(prediction < 0.5, 0, 1)

library(gmodels)
library(caret)

CrossTable(x = tele_norm_test$yyes, y = ANN_yyes_pred, prop.chisq=FALSE)

confusionMatrix(as.factor(ANN_yyes_pred), as.factor(tele_norm_test$yyes), positive = "1")


```

## Logistic Regrssion Model

```{r}
#Set a seed for random number generator for consistent output
test_set <- sample(1:nrow(tele_norm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 
# Create a train set and test set
#First the predictors
tele_train_log <- tele_norm[-test_set, ]
tele_test_log <- tele_norm[test_set, ]
library(gmodels)
library(caret)
firstmodel <- glm(yyes ~ age + jobblue.collar + jobservices + maritalsingle + defaultunknown +
                    contacttelephone + monthaug + 
                    monthdec + monthjun + monthmar + monthmay + monthnov + monthdec +
                    day_of_weekmon + day_of_weekwed + campaign + 
                    poutcomenonexistent + poutcomesuccess + emp.var.rate + 
                    cons.price.idx + cons.conf.idx + nr.employed + pdaysdummy + maritalsingle*age +
                    jobblue.collar*emp.var.rate + campaign*poutcomesuccess + campaign*nr.employed, 
                    data = tele_norm, family = "binomial")
summary(firstmodel)

prediction <- predict(firstmodel, tele_test_log)
LOG_yyes_pred <- ifelse(prediction < 0.5, 0, 1)
CrossTable(x = tele_test_log$yyes, y = LOG_yyes_pred, prop.chisq=FALSE)
confusionMatrix(as.factor(LOG_yyes_pred), as.factor(tele_test_log$yyes), positive = "1")


```

## Majority Vote Classification
```{r}
all <- KNN_yyes_pred + ANN_yyes_pred + LOG_yyes_pred
print(all)
```

